---
title: "Untitled"
author: "YI-CHENG, TAI"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(mvtnorm)
library(survival)
```

```{r}
## generate (Y, delta, X), where X is ternary and Y is lifetime with censoring
## sample size
size <- 500

## correlation of latent Gaussian distribution
rho <- 0.5 

## correlation matrix of latent Gaussian
corr.matrix <- matrix(c(1, rho, rho, 1), nrow = 2) 

## Cutoff points to make ternary variable
cut.off <- 0 

## Draw a random sample from the latent Gaussian distribution
Z <- rmvnorm(n = size, mean = c(0, 0), sigma = corr.matrix)

## Assume that h0(t)=exp(t), and make the lifetime variable
T1 <- exp(Z[, 1])

## Do discretization to make binary variable
X1 <- ifelse(Z[, 2] < cut.off, 0, 1)

## generate the censoring variable
C <- rexp(n = size, rate = 0.5)

## Make the censored observation for lifetime
Y1 <- ifelse(T1 < C, T1, C)

## Indicator to indicate that the lifetime is censored or not
delta <- ifelse(T1 < C, 1, 0)
```

#### The true distribution of H
$$
H(x, y) = Pr(X = x, T > y)
$$
```{r}
knot <- seq(0, 10, length.out = 500)
H.true <- matrix(nrow = length(knot), ncol = 3)
colnames(H.true) <- c("contr", "treat", "overall")

for(i in seq(1, length(knot))) {
  H.true[i, "contr"] <- pmvnorm(lower = c(-Inf, log(knot[i])),
                                upper = c(cut.off, Inf),
                                sigma = corr.matrix)[1]
  H.true[i, "treat"] <- pmvnorm(lower = c(cut.off, log(knot[i])),
                                upper = c(Inf, Inf),
                                sigma = corr.matrix)[1]
  H.true[i, "overall"] <- 1 - pnorm(q = log(knot[i]))
}

plot(knot, H.true[, "contr"], type = "l", ylim = c(0, 1))
points(knot, H.true[, "treat"], type = "l", lty = 2)
points(knot, H.true[, "overall"], type = "l", lty = 3)
legend("topright", legend = c("control", "treatment", "overall"), lty = 1:3)
```

```{r}
H.hat <- matrix(nrow = length(knot), ncol = 3)
colnames(H.hat) <- c("contr", "treat", "overall")

for(i in seq(1, length(knot))) {
  H.hat[i, "contr"] <- mean(X1 == 0 & T1 > knot[i])
  H.hat[i, "treat"] <- mean(X1 == 1 & T1 > knot[i])
  H.hat[i, "overall"] <- mean(T1 > knot[i])
}

plot(knot, H.hat[, "contr"], type = "l", ylim = c(0, 1))
points(knot, H.hat[, "treat"], type = "l", lty = 2)
points(knot, H.hat[, "overall"], type = "l", lty = 3)
legend("topright", legend = c("control", "treatment", "overall"), lty = 1:3)
```

```{r}
G.fit <- survfit(Surv(time = C, event = 1 - delta) ~ 1)
G_func <- stepfun(x = G.fit$time, y = c(1, G.fit$surv)) 

H.tilde <- matrix(nrow = length(knot), ncol = 3)
colnames(H.tilde) <- c("contr", "treat", "overall")

for(i in seq(1, length(knot))) {
  H.tilde[i, "contr"] <- mean(X1 == 0 & Y1 > knot[i]) / G_func(knot[i])
  H.tilde[i, "treat"] <- mean(X1 == 1 & Y1 > knot[i]) / G_func(knot[i])
  H.tilde[i, "overall"] <- mean(Y1 > knot[i]) / G_func(knot[i])
}

plot(knot, H.tilde[, "contr"], type = "l", ylim = c(0, 1))
points(knot, H.tilde[, "treat"], type = "l", lty = 2)
points(knot, H.tilde[, "overall"], type = "l", lty = 3)
legend("topright", legend = c("control", "treatment", "overall"), lty = 1:3)
```

```{r}
G.fit <- survfit(Surv(time = C, event = 1 - delta) ~ 1)
G_func <- stepfun(x = G.fit$time, y = c(1, G.fit$surv)) 

H.tilde <- matrix(nrow = length(knot), ncol = 3)
colnames(H.tilde) <- c("contr", "treat", "overall")

for(i in seq(1, length(knot))) {
  w <- 1 - pexp(knot[i], rate = 0.5)
  H.tilde[i, "contr"] <- mean(X1 == 0 & Y1 > knot[i]) / w
  H.tilde[i, "treat"] <- mean(X1 == 1 & Y1 > knot[i]) / w
  H.tilde[i, "overall"] <- mean(Y1 > knot[i]) / w
}

plot(knot, H.tilde[, "contr"], type = "l", ylim = c(0, 1))
points(knot, H.tilde[, "treat"], type = "l", lty = 2)
points(knot, H.tilde[, "overall"], type = "l", lty = 3)
legend("topright", legend = c("control", "treatment", "overall"), lty = 1:3)
```

```{r}
plot(knot, H.true[, "contr"], type = "l")
points(knot, H.hat[, "contr"], type = "l", lty = 2)
points(knot, H.tilde[, "contr"], type = "l", lty = 3)
legend("topright", legend = c("true", "hat", "tilde"), lty = 1:3)


plot(knot, H.true[, "treat"], type = "l")
points(knot, H.hat[, "treat"], type = "l", lty = 2)
points(knot, H.tilde[, "treat"], type = "l", lty = 3)
legend("topright", legend = c("true", "hat", "tilde"), lty = 1:3)


plot(knot, H.true[, "overall"], type = "l")
points(knot, H.hat[, "overall"], type = "l", lty = 2)
points(knot, H.tilde[, "overall"], type = "l", lty = 3)
legend("topright", legend = c("true", "hat", "tilde"), lty = 1:3)
```

```{r}
plot(G_func, ylim = c(0, 1))
```

