---
title: "Untitled"
author: "YI-CHENG, TAI"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(mvtnorm)
library(survival)
```

```{r}
## generate (Y, delta, X), where X is ternary and Y is lifetime with censoring
## sample size
size <- 500

## correlation of latent Gaussian distribution
rho <- -0.9

## correlation matrix of latent Gaussian
corr.matrix <- matrix(c(1, rho, rho, 1), nrow = 2) 

## Cutoff points to make ternary variable
cut.off <- 0 

## Draw a random sample from the latent Gaussian distribution
Z <- rmvnorm(n = size, mean = c(0, 0), sigma = corr.matrix)

## Assume that h0(t)=exp(t), and make the lifetime variable
T1 <- exp(Z[, 1])

## Do discretization to make binary variable
X1 <- ifelse(Z[, 2] < cut.off, 0, 1)

## generate the censoring variable
C <- rexp(n = size, rate = 0.5)

## Make the censored observation for lifetime
Y1 <- ifelse(T1 < C, T1, C)

## Indicator to indicate that the lifetime is censored or not
delta <- ifelse(T1 < C, 1, 0)
```

```{r}
mean(1 - delta)
```

```{r}
df.pair <- matrix(nrow = choose(n = size, k = 2), ncol = 8)

k <- 1
for(i in seq(1, size - 1)) {
  for(j in seq(i + 1, size)) {
    df.pair[k, ] <- c(X1[i], Y1[i], delta[i], T1[i], X1[j], Y1[j], delta[j], T1[j])
    k <- k + 1
  }
}
```

## empirical estimator
```{r}
H10.hat <- function(x, y, X1.obs = X1, T1.obs = T1) {
  return(mean(X1.obs == x & T1.obs > y))
}

H11.hat <- function(x, s, X1.obs = X1, T1.obs = T1) {
  return(mean(X1.obs == x & T1.obs == s))
}
```

## IPCW estimator
```{r}
# G.fit <- survfit(Surv(time = Y1, event = 1 - delta) ~ 1)
# G_func <- stepfun(x = G.fit$time, y = c(1, G.fit$surv))
# max(G.fit$time)
# 
# H10.hat <- function(x, y, X1.obs = X1, T1.obs = Y1) {
#   if(G_func(y) == 0) {
#     print(y)
#     # Sys.sleep(10)
#   }
#   
#   return(mean(X1.obs == x & T1.obs > y) / G_func(y))
# }
# 
# H11.hat <- function(x, y, X1.obs = X1, T1.obs = Y1) {
#   if(G_func(y) == 0) {
#     print(y)
#     # Sys.sleep(10)
#   }
#   
#   return(mean(X1.obs == x & T1.obs == y) / G_func(y))
# }
```


```{r}
c.hat <- numeric(nrow(df.pair))
d.hat <- numeric(nrow(df.pair))

for(k in seq(1, nrow(df.pair))) {
  if(df.pair[k, 1] > df.pair[k, 5]) {
    ## xi > xi'
    if(df.pair[k, 2] > df.pair[k, 6]) {
      ## yi > yi'
      H10.hat.i <- H10.hat(0, df.pair[k, 2])
      H10.hat.ip <- H10.hat(0, df.pair[k, 6])
      
      if(df.pair[k, 7] == 1) {
        c.hat[k] <- 1
        d.hat[k] <- 0
      } else if(df.pair[k, 3] == 1 & df.pair[k, 7] == 0) {
        d.hat[k] <- H10.hat.i / H10.hat.ip
        c.hat[k] <- 1 - d.hat[k]
      } else {
        t <- T1[T1 >= df.pair[k, 2]]
        integral.c <- numeric(length(t))
        integral.d <- numeric(length(t))
        
        for(m in seq(1, length(t))) {
          integral.c[m] <- (H10.hat.ip - H10.hat(0, t[m])) * H11.hat(1, t[m])
          integral.d[m] <- H10.hat(0, t[m]) * H11.hat(1, t[m])
        }
        
        c.hat[k] <- sum(integral.c) / H10.hat(1, df.pair[2]) / H10.hat.ip
        d.hat[k] <- sum(integral.d) / H10.hat(1, df.pair[2]) / H10.hat.ip
      }
      
    } else {
      ## yi < yi'
      H10.hat.i <- H10.hat(1, df.pair[k, 2])
      H10.hat.ip <- H10.hat(1, df.pair[k, 6])
      
      if(df.pair[k, 3] == 1) {
        c.hat[k] <- 0
        d.hat[k] <- 1
      } else if(df.pair[k, 3] == 0 & df.pair[k, 7] == 1) {
        c.hat[k] <- H10.hat.ip / H10.hat.i
        d.hat[k] <- 1 - c.hat[k]
      } else {
        t <- T1[T1 >= df.pair[k, 6]]
        integral.c <- numeric(length(t))
        integral.d <- numeric(length(t))
        
        for(m in seq(1, length(t))) {
          integral.c[m] <- (H10.hat(0, df.pair[k, 6]) - H10.hat(0, t[m])) * H11.hat(1, t[m])
          integral.d[m] <- (H10.hat.i - H10.hat(1, t[m])) * H11.hat(0, t[m])
        }
        c.hat[k] <- sum(integral.c) / H10.hat.i / H10.hat(0, df.pair[k, 6])
        d.hat[k] <- sum(integral.d) / H10.hat.i / H10.hat(0, df.pair[k, 6])
      }
      
    }
  }
  
  if(df.pair[k, 1] < df.pair[k, 5]) {
    ## xi < xi'
    
    if(df.pair[k, 2] > df.pair[k, 6]) {
      ## yi > yi'
      H10.hat.i <- H10.hat(1, df.pair[k, 2])
      H10.hat.ip <- H10.hat(1, df.pair[k, 6])
      
      if(df.pair[k, 7] == 1) {
        c.hat[k] <- 0
        d.hat[k] <- 1
      } else if(df.pair[k, 3] == 1 & df.pair[k, 7] == 0) {
        c.hat[k] <- H10.hat.i / H10.hat.ip
        d.hat[k] <- 1 - c.hat[k]
      } else {
        t <- T1[T1 >= df.pair[k, 2]]
        integral.c <- numeric(length(t))
        integral.d <- numeric(length(t))
        
        for(m in seq(1, length(t))) {
          integral.c[m] <- H10.hat(1, t[m]) * H11.hat(0, t[m])
          integral.d[m] <- (H10.hat.ip - H10.hat(1, t[m])) * H11.hat(0, t[m])
        }
        c.hat[k] <- sum(integral.c) / H10.hat(0, df.pair[2]) / H10.hat.ip
        d.hat[k] <- sum(integral.d) / H10.hat(0, df.pair[2]) / H10.hat.ip 
      }
      
    } else {
      ## yi < yi'
      H10.hat.i <- H10.hat(0, df.pair[k, 2])
      H10.hat.ip <- H10.hat(0, df.pair[k, 6])
      
      if(df.pair[k, 3] == 1) {
        c.hat[k] <- 1
        d.hat[k] <- 0
      } else if(df.pair[k, 3] == 0 & df.pair[k, 7] == 1) {
        d.hat[k] <- H10.hat.ip / H10.hat.i
        c.hat[k] <- 1 - d.hat[k]
      } else {
        s <- T1[T1 >= df.pair[k, 6]]
        integral.c <- numeric(length(s))
        integral.d <- numeric(length(s))
        
        for(m in seq(1, length(s))) {
          integral.c[m] <- (H10.hat.i - H10.hat(0, s[m])) * H11.hat(1, s[m])
          integral.d[m] <- (H10.hat(1, df.pair[k, 6]) - H10.hat(1, s[m])) * H11.hat(0, s[m])
        }
        c.hat[k] <- sum(integral.c) / H10.hat(1, df.pair[6]) / H10.hat.i
        d.hat[k] <- sum(integral.d) / H10.hat(1, df.pair[6]) / H10.hat.i
      }
      
    }
  }
  
  if(abs(c.hat[k]) > 1 | abs(d.hat[k]) > 1) {
    print(c(k, c.hat[k], d.hat[k]))
  }
}

sum(abs(c.hat) > 1)
sum(abs(d.hat) > 1)
sum(is.na(c.hat))
sum(is.na(d.hat))
```

```{r}
df.pair[580, ]

data.frame(c.hat,
           d.hat,
           est = c.hat - d.hat,
           true = (df.pair[, 1] - df.pair[, 5]) * ifelse(df.pair[, 4] > df.pair[, 8], 1, -1))[580, ]
```


```{r}
sum(c.hat - d.hat)
sum((df.pair[, 1] - df.pair[, 5]) * ifelse(df.pair[, 4] > df.pair[, 8], 1, -1))
sum(c.hat - d.hat) / sum(X1 == 1) / sum(X1 == 0)
sum(c.hat - d.hat) / choose(size, 2)
sum((df.pair[, 1] - df.pair[, 5]) * ifelse(df.pair[, 4] > df.pair[, 8], 1, -1)) / choose(size, 2)
```

```{r}
4 * pmvnorm(lower = c(-Inf, -Inf), upper = c(0, 0), corr = matrix(c(1, -0.9 / sqrt(2), -0.9 / sqrt(2), 1), nrow = 2)) - 2 * pnorm(0)
```


## rate of C: 0.07, 0.28, 0.65, 1.4, 4
```{r}
iter <- 1
sim <- replicate(n = 100, expr = {
  ## generate (Y, delta, X), where X is binary and Y is lifetime with censoring
  size <- 500
  rho <- 0.9
  corr.matrix <- matrix(c(1, rho, rho, 1), nrow = 2)
  cut.off <- 0
  Z <- rmvnorm(n = size, mean = c(0, 0), sigma = corr.matrix)
  T1 <- exp(Z[, 1])
  X1 <- ifelse(Z[, 2] < cut.off, 0, 1)
  C <- rexp(n = size, rate = 0.3)
  Y1 <- ifelse(T1 < C, T1, C)
  delta <- ifelse(T1 < C, 1, 0)
  
  df.pair <- matrix(nrow = choose(n = size, k = 2), ncol = 8)
  k <- 1
  for(i in seq(1, size - 1)) {
    for(j in seq(i + 1, size)) {
      df.pair[k, ] <- c(X1[i], Y1[i], delta[i], T1[i], X1[j], Y1[j], delta[j], T1[j])
      k <- k + 1
    }
  }
  
  H10.hat <- function(x, y, X1.obs = X1, T1.obs = T1) {
    return(mean(X1.obs == x & T1.obs > y))
  }
  
  H11.hat <- function(x, s, X1.obs = X1, T1.obs = T1) {
    return(mean(X1.obs == x & T1.obs == s))
  }
  
  ## imputation
  c.hat <- numeric(nrow(df.pair))
  d.hat <- numeric(nrow(df.pair))
  
  for(k in seq(1, nrow(df.pair))) {
    if(df.pair[k, 1] > df.pair[k, 5]) {
      ## xi > xi'
      if(df.pair[k, 2] > df.pair[k, 6]) {
        ## yi > yi'
        H10.hat.i <- H10.hat(0, df.pair[k, 2])
        H10.hat.ip <- H10.hat(0, df.pair[k, 6])
        
        if(df.pair[k, 7] == 1) {
          c.hat[k] <- 1
          d.hat[k] <- 0
        } else if(df.pair[k, 3] == 1 & df.pair[k, 7] == 0) {
          d.hat[k] <- H10.hat.i / H10.hat.ip
          c.hat[k] <- 1 - d.hat[k]
        } else {
          t <- T1[T1 >= df.pair[k, 2]]
          integral.c <- numeric(length(t))
          integral.d <- numeric(length(t))
          
          for(m in seq(1, length(t))) {
            integral.c[m] <- (H10.hat.ip - H10.hat(0, t[m])) * H11.hat(1, t[m])
            integral.d[m] <- H10.hat(0, t[m]) * H11.hat(1, t[m])
          }
          
          c.hat[k] <- sum(integral.c) / H10.hat(1, df.pair[2]) / H10.hat.ip
          d.hat[k] <- sum(integral.d) / H10.hat(1, df.pair[2]) / H10.hat.ip
        }
        
      } else {
        ## yi < yi'
        H10.hat.i <- H10.hat(1, df.pair[k, 2])
        H10.hat.ip <- H10.hat(1, df.pair[k, 6])
        
        if(df.pair[k, 3] == 1) {
          c.hat[k] <- 0
          d.hat[k] <- 1
        } else if(df.pair[k, 3] == 0 & df.pair[k, 7] == 1) {
          c.hat[k] <- H10.hat.ip / H10.hat.i
          d.hat[k] <- 1 - c.hat[k]
        } else {
          t <- T1[T1 >= df.pair[k, 6]]
          integral.c <- numeric(length(t))
          integral.d <- numeric(length(t))
          
          for(m in seq(1, length(t))) {
            integral.c[m] <- (H10.hat(0, df.pair[k, 6]) - H10.hat(0, t[m])) * H11.hat(1, t[m])
            integral.d[m] <- (H10.hat.i - H10.hat(1, t[m])) * H11.hat(0, t[m])
          }
          c.hat[k] <- sum(integral.c) / H10.hat.i / H10.hat(0, df.pair[k, 6])
          d.hat[k] <- sum(integral.d) / H10.hat.i / H10.hat(0, df.pair[k, 6])
        }
        
      }
    }
    
    if(df.pair[k, 1] < df.pair[k, 5]) {
      ## xi < xi'
      
      if(df.pair[k, 2] > df.pair[k, 6]) {
        ## yi > yi'
        H10.hat.i <- H10.hat(1, df.pair[k, 2])
        H10.hat.ip <- H10.hat(1, df.pair[k, 6])
        
        if(df.pair[k, 7] == 1) {
          c.hat[k] <- 0
          d.hat[k] <- 1
        } else if(df.pair[k, 3] == 1 & df.pair[k, 7] == 0) {
          c.hat[k] <- H10.hat.i / H10.hat.ip
          d.hat[k] <- 1 - c.hat[k]
        } else {
          t <- T1[T1 >= df.pair[k, 2]]
          integral.c <- numeric(length(t))
          integral.d <- numeric(length(t))
          
          for(m in seq(1, length(t))) {
            integral.c[m] <- H10.hat(1, t[m]) * H11.hat(0, t[m])
            integral.d[m] <- (H10.hat.ip - H10.hat(1, t[m])) * H11.hat(0, t[m])
          }
          c.hat[k] <- sum(integral.c) / H10.hat(0, df.pair[2]) / H10.hat.ip
          d.hat[k] <- sum(integral.d) / H10.hat(0, df.pair[2]) / H10.hat.ip 
        }
        
      } else {
        ## yi < yi'
        H10.hat.i <- H10.hat(0, df.pair[k, 2])
        H10.hat.ip <- H10.hat(0, df.pair[k, 6])
        
        if(df.pair[k, 3] == 1) {
          c.hat[k] <- 1
          d.hat[k] <- 0
        } else if(df.pair[k, 3] == 0 & df.pair[k, 7] == 1) {
          d.hat[k] <- H10.hat.ip / H10.hat.i
          c.hat[k] <- 1 - d.hat[k]
        } else {
          s <- T1[T1 >= df.pair[k, 6]]
          integral.c <- numeric(length(s))
          integral.d <- numeric(length(s))
          
          for(m in seq(1, length(s))) {
            integral.c[m] <- (H10.hat.i - H10.hat(0, s[m])) * H11.hat(1, s[m])
            integral.d[m] <- (H10.hat(1, df.pair[k, 6]) - H10.hat(1, s[m])) * H11.hat(0, s[m])
          }
          c.hat[k] <- sum(integral.c) / H10.hat(1, df.pair[6]) / H10.hat.i
          d.hat[k] <- sum(integral.d) / H10.hat(1, df.pair[6]) / H10.hat.i
        }
        
      }
    }
    
    if(abs(c.hat[k]) > 1 | abs(d.hat[k]) > 1) {
      # print(c(k, c.hat[k], d.hat[k]))
    }
  }
  
  tau.imputed <- sum(c.hat) - sum(d.hat)
  tau.true <- sum((df.pair[, 1] - df.pair[, 5]) * ifelse(df.pair[, 4] > df.pair[, 8], 1, -1))
  print(iter)
  iter <- iter + 1
  
  return(tau.imputed - tau.true)
})
```

```{r}
hist(sim, main = "rho:0.9, censoring rate:0.9", xlab = NA)
mean(sim, na.rm = TRUE)
sd(sim, na.rm = TRUE)
```

#### examine the validity of the estimate of integral
**case 1** <br>
$X_i = 1, X_{i'} = 0, y_i > y_{i'}, \delta_i = \delta_{i'} = 0$

$$
\int_{y_i}^{\infty} [H_{10}(0, y_{i'}) - H_{10}(0, t)] H_{11}(1, t) dt
$$

##### naive estimator (uncensored)
$$
\hat{H}_{11}(x, t) = \frac{1}{n} \sum_{i=1}^n I(X_i = x, T_i = t)
$$
```{r}
i <- seq(1, nrow(df.pair))[df.pair[, 3] == 0 & df.pair[, 7] == 0 & df.pair[, 1] > df.pair[, 5] & df.pair[, 2] > df.pair[, 6]][1]

t <- T1[T1 >= df.pair[i, 2]]
integral <- numeric(length(t))

for(k in seq(1, length(t))) {
  integral[k] <- (H10.hat(x = 0, y = df.pair[i, 6]) - H10.hat(x = 0, y = t[k])) * H11.hat(x = 1, s = t[k])
}

sum(integral)

## true value of integral
t <- seq(log(df.pair[i, 2]), 4, length.out = 500)
integral.true <- numeric(500 - 1)

for(m in seq(1, length(integral.true))) {
  integral.true[m] <- pmvnorm(lower = c(-Inf, log(df.pair[i, 6])), upper = c(0, t[m]), corr = corr.matrix)
  integral.true[m] <- integral.true[m] * pmvnorm(lower = c(0, t[m]), upper = c(Inf, t[m + 1]), corr = corr.matrix)
}

sum(integral.true)
```


