---
title: "GC_Cross"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(survival)
```

## H0: T is independent of X1
#### Data Generation
```{r}
size <- 200
X1 <- rbinom(n = size, size = 1, prob = 0.5)
T1 <- rweibull(n = size, shape = 2, scale = 1)
C <- rexp(n = size, rate = 0.3)
Y1 <- ifelse(T1 < C, T1, C)
delta <- ifelse(T1 < C, 1, 0)
```

```{r}
C.rate <- 0.68
size <- 200
set.seed(20200630)
sim <- replicate(n = 5000, expr = {
  ## generate (Y, delta, X), where X is binary and Y is lifetime with censoring
  X1 <- rbinom(n = size, size = 1, prob = 0.5)
  T11 <- rweibull(n = size, shape = 2, scale = 1.2)
  T12 <- rweibull(n = size, shape = 0.5, scale = 2)
  T1 <- ifelse(X1 == 1, T11, T12)
  C <- rexp(n = size, rate = C.rate)
  Y1 <- ifelse(T1 < C, T1, C)
  delta <- ifelse(T1 < C, 1, 0)
  df.pair <- matrix(nrow = choose(n = size, k = 2), ncol = 8)
  k <- 1
  for(i in seq(1, size - 1)) {
    for(j in seq(i + 1, size)) {
      df.pair[k, ] <- c(X1[i], Y1[i], delta[i], T1[i], X1[j], Y1[j], delta[j], T1[j])
      k <- k + 1
    }
  }
  
  tau.true <- sum((df.pair[, 1] - df.pair[, 5]) * ifelse(df.pair[, 4] > df.pair[, 8], 1, -1))
  n1 <- sum(X1)
  n0 <- size - n1

  return(list(tau.true / n0 / n1, mean(delta), mean(delta[X1 == 1]), mean(delta[X1 == 0])))
})

mean(unlist(sim[1, ]))
mean(unlist(sim[2, ]))
mean(unlist(sim[3, ]))
mean(unlist(sim[4, ]))
```

```{r}
curve(1 - pweibull(x, shape = 2, scale = 1.2), from = 0, to = 10, xlab = "t", ylab = "survival")
curve(1 - pweibull(x, shape = 0.5, scale = 2), from = 0, to = 10, lty = 2, add = TRUE)
legend("topright", legend = c("k=2, lambda=1.2", "k=0.5, lambda=2"), lty = c(1, 2))
```

```{r}
curve(dweibull(x, shape = 2, scale = 1.2), from = 0, to = 5, xlab = "t", ylab = "density",
      ylim = c(0, 1.5))
curve(dweibull(x, shape = 0.5, scale = 2), from = 0, to = 5, lty = 2, add = TRUE)
legend("topright", legend = c("k=2, lambda=1.2", "k=0.5, lambda=2"), lty = c(1, 2))
```

```{r}
par(mfrow = c(1, 2))
curve(1 - pweibull(x, shape = 2, scale = 1.2), from = 0, to = 8, xlab = "t", ylab = "survival")
curve(1 - pweibull(x, shape = 0.5, scale = 2), from = 0, to = 8, lty = 2, add = TRUE)
legend("topright", legend = c("k=2, lambda=1.2", "k=0.5, lambda=2"), lty = c(1, 2))

curve(dweibull(x, shape = 2, scale = 1.2), from = 0, to = 5, xlab = "t", ylab = "density",
      ylim = c(0, 1.5))
curve(dweibull(x, shape = 0.5, scale = 2), from = 0, to = 5, lty = 2, add = TRUE)
legend("topright", legend = c("k=2, lambda=1.2", "k=0.5, lambda=2"), lty = c(1, 2))
```


## c.rate: 0.12, 0.85
#### imputation
```{r}
C.rate <- 0.12
size <- 200
set.seed(20200630)
sim <- replicate(n = 500, expr = {
  ## generate (Y, delta, X), where X is binary and Y is lifetime with censoring
  X1 <- rbinom(n = size, size = 1, prob = 0.5)
  T1 <- rweibull(n = size, shape = 2, scale = 1)
  C <- rexp(n = size, rate = C.rate)
  Y1 <- ifelse(T1 < C, T1, C)
  delta <- ifelse(T1 < C, 1, 0)
  
  return(impute_binary_tau(Y1, delta, X1, T1))
})
```

```{r}
saveRDS(sim, "./Crossing_RDS/crossingNull_0dot9.rds")
```

```{r}
readRDS("./Crossing_RDS/crossingNull_0dot9.rds")
readRDS("./Crossing_RDS/crossingNull_0dot5.rds")
```

```{r}
hist(unlist(sim["bias", ]), xlab = NA)

par(mfrow = c(1, 5))
hist((unlist(sim["tau.hat", ]) / sd(unlist(sim["tau.hat", ]))) ^ 2,
     main = "proposed",
     xlab = "chisq",
     freq = FALSE)
curve(dchisq(x, df = 1), from = 0, to = 50, add = TRUE)

hist(unlist(sim["logrank", ]), main = "logrank", xlab = "chisq", freq = FALSE)
curve(dchisq(x, df = 1), from = 0, to = 50, add = TRUE)

hist(unlist(sim["gehan", ]), main = "Gehan", xlab = "chisq", freq = FALSE)
curve(dchisq(x, df = 1), from = 0, to = 50, add = TRUE)

hist(unlist(sim["wilcox", ]), main = "Wilcoxon", xlab = "chisq", freq = FALSE)
curve(dchisq(x, df = 1), from = 0, to = 50, add = TRUE)

hist(unlist(sim["gehan2", ]), main = "Gehan2", xlab = "z", freq = FALSE)
curve(dnorm(x, mean = 0, sd = 1), from = -5, to = 5, add = TRUE)
```

```{r}
mean(unlist(sim["bias", ]))
sd(unlist(sim["bias", ]))
mean(unlist(sim["tau.true", ]))
mean(unlist(sim["tau.hat", ]))
mean(unlist(sim["C.rate", ]))
```

```{r}
proposed.ts <- (unlist(sim["tau.hat", ]) / sd(unlist(sim["tau.hat", ]))) ^ 2
mean(proposed.ts > qchisq(0.95, df = 1))
mean(unlist(sim["logrank", ]) > qchisq(0.95, df = 1))
mean(unlist(sim["gehan", ]) > qchisq(0.95, df = 1))
mean(unlist(sim["wilcox", ]) > qchisq(0.95, df = 1))
mean(abs(unlist(sim["gehan2", ])) > qnorm(0.975, mean = 0, sd = 1))
```

```{r}
sd(proposed.ts > qchisq(0.95, df = 1))
sd(unlist(sim["logrank", ]) > qchisq(0.95, df = 1))
sd(unlist(sim["gehan", ]) > qchisq(0.95, df = 1))
sd(unlist(sim["wilcox", ]) > qchisq(0.95, df = 1))
sd(abs(unlist(sim["gehan2", ])) > qnorm(0.975, mean = 0, sd = 1))
```


#### Second case: tau = 0 but crossing
#### c.rate: 0.05, 0.68
```{r}
C.rate <- 0.68
size <- 200
set.seed(20200630)
sim <- replicate(n = 500, expr = {
  ## generate (Y, delta, X), where X is binary and Y is lifetime with censoring
  X1 <- rbinom(n = size, size = 1, prob = 0.5)
  T11 <- rweibull(n = size, shape = 2, scale = 1.2)
  T12 <- rweibull(n = size, shape = 0.5, scale = 2)
  T1 <- ifelse(X1 == 1, T11, T12)
  C <- rexp(n = size, rate = C.rate)
  Y1 <- ifelse(T1 < C, T1, C)
  delta <- ifelse(T1 < C, 1, 0)
  
  return(impute_binary_tau(Y1, delta, X1, T1))
})
```

```{r}
X1 <- rbinom(n = size, size = 1, prob = 0.5)
T11 <- rweibull(n = size, shape = 2, scale = 1.2)
T12 <- rweibull(n = size, shape = 0.5, scale = 2)
T1 <- ifelse(X1 == 1, T11, T12)
C <- rexp(n = size, rate = C.rate)
Y1 <- ifelse(T1 < C, T1, C)
delta <- ifelse(T1 < C, 1, 0)

Gehan_func(Y1, delta, X1)
MannWhitney_func(Y1, delta, X1, T1)
impute_binary_tau(Y1, delta, X1, T1)$tau.hat
```


```{r}
saveRDS(sim, file = "./Crossing_RDS/crossing_0dot5_0_case2")
```

```{r}
sim <- readRDS(file = "./Crossing_RDS/crossing_0dot9_0_case2")
sim <- readRDS(file = "./Crossing_RDS/crossing_0dot5_0_case2")
```

```{r}
hist(unlist(sim["bias", ]), xlab = NA)

par(mfrow = c(1, 5))
hist((unlist(sim["tau.hat", ]) / sd(unlist(sim["tau.hat", ]))) ^ 2,
     main = "proposed",
     xlab = "chisq",
     freq = FALSE)
curve(dchisq(x, df = 1), from = 0, to = 50, add = TRUE)

hist(unlist(sim["logrank", ]), main = "logrank", xlab = "chisq", freq = FALSE)
curve(dchisq(x, df = 1), from = 0, to = 50, add = TRUE)

hist(unlist(sim["gehan", ]), main = "Gehan", xlab = "chisq", freq = FALSE)
curve(dchisq(x, df = 1), from = 0, to = 50, add = TRUE)

hist(unlist(sim["wilcox", ]), main = "Wilcoxon", xlab = "chisq", freq = FALSE)
curve(dchisq(x, df = 1), from = 0, to = 50, add = TRUE)

hist(unlist(sim["gehan2", ]), main = "Gehan2", xlab = "z", freq = FALSE)
curve(dnorm(x, mean = 0, sd = 1), from = -5, to = 5, add = TRUE)
```

```{r}
mean(unlist(sim["bias", ]))
sd(unlist(sim["bias", ]))
mean(unlist(sim["tau.true", ]))
mean(unlist(sim["tau.hat", ]))
mean(unlist(sim["C.rate", ]))
```

```{r}
proposed.ts <- (unlist(sim["tau.hat", ]) / sd(unlist(sim["tau.hat", ]))) ^ 2
mean(proposed.ts > qchisq(0.95, df = 1))
mean(unlist(sim["logrank", ]) > qchisq(0.95, df = 1))
mean(unlist(sim["gehan", ]) > qchisq(0.95, df = 1))
mean(unlist(sim["wilcox", ]) > qchisq(0.95, df = 1))
mean(abs(unlist(sim["gehan2", ])) > qnorm(0.975, mean = 0, sd = 1))
```

```{r}
sd(proposed.ts > qchisq(0.95, df = 1))
sd(unlist(sim["logrank", ]) > qchisq(0.95, df = 1))
sd(unlist(sim["gehan", ]) > qchisq(0.95, df = 1))
sd(unlist(sim["wilcox", ]) > qchisq(0.95, df = 1))
sd(abs(unlist(sim["gehan2", ])) > qnorm(0.975, mean = 0, sd = 1))
```

#### Third case: tau is not zero and and the survival functions are crossing
```{r}
C.rate <- 0.05
size <- 200
set.seed(20200630)
sim <- replicate(n = 500, expr = {
  ## generate (Y, delta, X), where X is binary and Y is lifetime with censoring
  X1 <- rbinom(n = size, size = 1, prob = 0.5)
  T11 <- rweibull(n = size, shape = 4, scale = 1.5)
  T12 <- rweibull(n = size, shape = 0.5, scale = 2)
  T1 <- ifelse(X1 == 1, T11, T12)
  C <- rexp(n = size, rate = C.rate)
  Y1 <- ifelse(T1 < C, T1, C)
  delta <- ifelse(T1 < C, 1, 0)
  
  impute.tau <- impute_binary_tau(Y1, delta, X1, T1)
  
  return(impute.tau)
})
```

```{r}
saveRDS(sim, file = "./Crossing_RDS/crossing_0dot9_0dot1_case3.rds")
```

```{r}
sim <- readRDS(file = "./Crossing_RDS/crossing_0dot9_0dot5_case3.rds")
```

```{r}
hist(unlist(sim["bias", ]), xlab = NA)

par(mfrow = c(1, 4))
hist((unlist(sim["tau.hat", ]) / sd(unlist(sim["tau.hat", ]))) ^ 2,
     main = "proposed",
     xlab = "chisq",
     freq = FALSE)
curve(dchisq(x, df = 1), from = 0, to = 50, add = TRUE)

hist(unlist(sim["logrank", ]), main = "logrank", xlab = "chisq", freq = FALSE)
curve(dchisq(x, df = 1), from = 0, to = 50, add = TRUE)

hist(unlist(sim["gehan", ]), main = "Gehan", xlab = "chisq", freq = FALSE)
curve(dchisq(x, df = 1), from = 0, to = 50, add = TRUE)

hist(unlist(sim["wilcox", ]), main = "Wilcoxon", xlab = "chisq", freq = FALSE)
curve(dchisq(x, df = 1), from = 0, to = 50, add = TRUE)
```

```{r}
mean(unlist(sim["bias", ]))
sd(unlist(sim["bias", ]))
mean(unlist(sim["tau.true", ]))
mean(unlist(sim["tau.hat", ]))
mean(unlist(sim["C.rate", ]))
```

```{r}
proposed.ts <- (unlist(sim["tau.hat", ]) / sd(unlist(sim["tau.hat", ]))) ^ 2
mean(proposed.ts > qchisq(0.95, df = 1))
mean(unlist(sim["logrank", ]) > qchisq(0.95, df = 1))
mean(unlist(sim["gehan", ]) > qchisq(0.95, df = 1))
mean(unlist(sim["wilcox", ]) > qchisq(0.95, df = 1))
```

```{r}
sd(proposed.ts > qchisq(0.95, df = 1))
sd(unlist(sim["logrank", ]) > qchisq(0.95, df = 1))
sd(unlist(sim["gehan", ]) > qchisq(0.95, df = 1))
sd(unlist(sim["wilcox", ]) > qchisq(0.95, df = 1))
```




#### Fourth case: tau is not zero and the survival functions are not crossing
```{r}
C.rate <- 0.06
size <- 200
set.seed(20200630)
sim <- replicate(n = 500, expr = {
  ## generate (Y, delta, X), where X is binary and Y is lifetime with censoring
  X1 <- rbinom(n = size, size = 1, prob = 0.5)
  T11 <- rweibull(n = size, shape = 2, scale = 2.2)
  T12 <- rweibull(n = size, shape = 2, scale = 2)
  T1 <- ifelse(X1 == 1, T11, T12)
  C <- rexp(n = size, rate = C.rate)
  Y1 <- ifelse(T1 < C, T1, C)
  delta <- ifelse(T1 < C, 1, 0)
  
  impute.tau <- impute_binary_tau(Y1, delta, X1, T1)
  
  return(impute.tau)
})
```

```{r}
saveRDS(sim, file = "./Crossing_RDS/crossing_0dot9_0dot1_case4.rds")
```

```{r}
sim <- readRDS(file = "./Crossing_RDS/crossing_0dot9_0dot5_case4.rds")
```

```{r}
hist(unlist(sim["bias", ]), xlab = NA)

par(mfrow = c(1, 4))
hist((unlist(sim["tau.hat", ]) / sd(unlist(sim["tau.hat", ]))) ^ 2,
     main = "proposed",
     xlab = "chisq",
     freq = FALSE)
curve(dchisq(x, df = 1), from = 0, to = 50, add = TRUE)

hist(unlist(sim["logrank", ]), main = "logrank", xlab = "chisq", freq = FALSE)
curve(dchisq(x, df = 1), from = 0, to = 50, add = TRUE)

hist(unlist(sim["gehan", ]), main = "Gehan", xlab = "chisq", freq = FALSE)
curve(dchisq(x, df = 1), from = 0, to = 50, add = TRUE)

hist(unlist(sim["wilcox", ]), main = "Wilcoxon", xlab = "chisq", freq = FALSE)
curve(dchisq(x, df = 1), from = 0, to = 50, add = TRUE)
```

```{r}
mean(unlist(sim["bias", ]))
sd(unlist(sim["bias", ]))
mean(unlist(sim["tau.true", ]))
mean(unlist(sim["tau.hat", ]))
mean(unlist(sim["C.rate", ]))
```

```{r}
proposed.ts <- (unlist(sim["tau.hat", ]) / sd(unlist(sim["tau.hat", ]))) ^ 2
mean(proposed.ts > qchisq(0.95, df = 1))
mean(unlist(sim["logrank", ]) > qchisq(0.95, df = 1))
mean(unlist(sim["gehan", ]) > qchisq(0.95, df = 1))
mean(unlist(sim["wilcox", ]) > qchisq(0.95, df = 1))
```

```{r}
sd(proposed.ts > qchisq(0.95, df = 1))
sd(unlist(sim["logrank", ]) > qchisq(0.95, df = 1))
sd(unlist(sim["gehan", ]) > qchisq(0.95, df = 1))
sd(unlist(sim["wilcox", ]) > qchisq(0.95, df = 1))
```

